sudo apt-get update;
sudo apt-get upgrade;
sudo apt-get install make m4 gcc aspcud curl bubblewrap;
sudo apt-get install ocaml opam;
sudo apt-get install -qq -yy libgmp-dev libhidapi-dev pkg-config;
wget https://raw.github.com/ocaml/opam/master/shell/opam_installer.sh -O — | sh -s /usr/local/bin;
sh <(curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh);
wget https://gitlab.com/tezos/tezos/-/archive/betanet/tezos-betanet.tar.gz;
tar -zxvf tezos-betanet.tar.gz;
cd tezos-betanet;
opam init;
opam update;
opam switch create 4.06.1;
opam switch set 4.06.1;
eval $(opam config env);
make build-deps;
make;
./tezos-node identity generate;
./tezos-node config init;
./tezos-node config update --rpc-addr=127.0.0.1:8732;
./tezos-node run;